### ISSUE TITLE
Rajouter les bornes de chargement de véhicules électriques

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/osmontrouge#1]

**Comment by francois2metz** [comment]
Done f36a32084bbecd15721196b842ad0a0fe575bdde

**Comment by overflorian** [comment]
Je trouve que les icones utilisées sont trop voyantes en zoom large (de 16 à 18) et pas assez identifiable en zoom plus proche. Tu pourrais peut-être utiliser cette icone ? https://github.com/osmontrouge/osm-liberty/blob/gh-pages/svgs/svgs_iconset/charging_station_11.svg
Ceci dit elle reste également bleue, ce qui ne colle pas vraiment avec le thème utilisé actuellement.

**Comment by francois2metz** [comment]
Je peux la mettre dans la même couleur que les autres icones pour le rendu dans la carte. Pour la taille c'est effectivement curieux. Je vais regarder si je n'ai pas un souci.

**Comment by francois2metz** [comment]
Hop c'est changé. Tu peux regarder et me dire ce que t'en pense ?
