### ISSUE TITLE
Rendre les murs et clôtures

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#10]
Dans l'idée d'avoir un rendu affichant les éléments micro-mappés, il serait bon de rendre barrier=wall et barrier=fence.

**Comment by francois2metz** [comment]
Oui effectivement. Actuellement ce n'est pas dans les tuiles.

**Comment by francois2metz** [comment]
Les murs et les clôtures sont désormais rendu :
![Screenshot_2019-07-27 OSMontrouge](https://user-images.githubusercontent.com/86659/61994736-b5901f80-b07e-11e9-9391-87680c92c36c.png)
