### ISSUE TITLE
Rendre les carrés du cimetière

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#11]
Hey,
Est-ce que ça vaudrait pas le coup d'afficher les différents secteurs du cimetière ? J'imagine une couleur un peu plus foncés que pour landuse=cemetery

Détails :
J'ai tracé tous les cemetery=sector
Je les ai nommé avec addr:place=*
Les carrés militaires ont également le tag sector=military
https://www.openstreetmap.org/way/665905648

**Comment by francois2metz** [comment]
Je regarde pour intégrer cela. Pour le `add:place` un `name` ne serait pas plus adapté ?

**Comment by francois2metz** [comment]
J'ai testé de mettre une couleur spécifique, mais ca ne rend pas grad choses, puisque tout le cimetière a des secteurs. Je propose de plutôt mettre le nom de chaque secteur. Qu'en pense tu ?

Le rendu de test avec les secteurs en rouge pour marquer la différence
![Screenshot_2019-07-28 Maputnik](https://user-images.githubusercontent.com/86659/62007583-7087ee00-b14f-11e9-885c-fac5c6ef2ce8.png)

**Comment by overflorian** [comment]
En effet, c'est moche. N'affichons donc que le name. Je propose de l'afficher à partir du zoom 18, comme les arbres.

**Comment by francois2metz** [comment]
Ok. On fait un truc pour changer le `addr:place` ?

**Comment by overflorian** [comment]
Je voulais être sympa avec mapnik mais aller, "on ne mappe pas pour le rendu".
J'ai tout [basculé en name](https://www.openstreetmap.org/changeset/72929905), tu peux te faire plaisir.

**Comment by francois2metz** [comment]
En prod.

![Screenshot_2019-08-02 OSMontrouge](https://user-images.githubusercontent.com/86659/62390612-fdbdaf00-b562-11e9-8511-ec1c76886b86.png)

**Comment by overflorian** [comment]
le rendu déchire, merci

**Comment by overflorian** [comment]
Affiché à un zoom très large, il semble que les noms des carrés ne font pas beaucoup de sens :
![Capture du 2019-08-18 10-02-07](https://user-images.githubusercontent.com/11553211/63221864-5ca83880-c19f-11e9-8edc-645372ced20a.png)

Je propose de ne les afficher qu'à partir du niveau de zoom 16.

**Comment by francois2metz** [comment]
L'ensemble des POIs s'affiche de la même façon. Je ne compte pas faire de rendu spécifique pour ce genre de choses.
