### ISSUE TITLE
Afficher les bâtiments en 3D

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#12]
Hello,
Je vois que les bâtiments ne s'affichent plus en 3D. J'ai passé pas mal de temps à renseigner le nombre d'étages sur les bâtiments, et je trouve que ça apporte un plus au rendu.

Tu penses rétablir cela ou bien est-ce lié à des contraintes techniques suites aux différents développements récents ?

**Comment by francois2metz** [comment]
Il faut utiliser le thème liberty dans le sélecteur de style dans la partie droite.

**Comment by overflorian** [comment]
ah ! j'aime.
Je propose de changer le wording :

- Bright => Plan
- Liberty => 3 dimensions

**Comment by francois2metz** [comment]
J'ai fait ça et j'en ai profité de supprimer liberty et faire le rendu 3d dans une version de bright parce que je ne maintenais pas liberty.

**Comment by overflorian** [comment]
Ok cool, ça fonctionne :)
Mais que sont ces couleurs criardes qui apparaissent sur les bâtiments en 3D tout d'un coup ? #Innovation

![Capture du 2019-08-06 11-37-19](https://user-images.githubusercontent.com/11553211/62529284-a22f4200-b83e-11e9-9956-5c9727141f26.png)

**Comment by francois2metz** [comment]
Il s'agit de la couleur du batiment à partir du tag material. Patch original de @frodrigo https://github.com/openmaptiles/klokantech-3d-gl-style/pull/8

**Comment by frodrigo** [comment]
Colueur explicite ou à défaut material.

**Comment by overflorian** [comment]
Ok, je comprends maintenant le but recherché et la raison de l'implémentation. J'avoue avoir été très surpris par ce choix graphique et un peu dérouté aussi.

J'ai deux objections :

1. Je doute que beaucoup de monde fasse **le lien entre la couleur sur la carte et la couleur véritable du bâtiment**. Les couleurs utilisées et la manière de l'implémenter (en particulier le fait que le toit soit aussi en couleur) me laissent à penser que l'utilisateur comprendra au contraire que nous souhaitons mettre en valeur ces bâtiment car ils ont un attrait particulier autre que la couleur de façade.
Il me semblerait ainsi plus lisible et utile d'highlighter par exemple les bâtiments publics, les services en particulier (sport, tourisme, commerces, ... you name it)

A titre d'exemple, Google Maps utilise les couleurs de bâtiment avec parcimonie, à ma connaissance uniquement pour les commerces (pour les environnement outdoor) :
![Capture du 2019-08-08 09-17-55](https://user-images.githubusercontent.com/11553211/62682905-843c1b80-b9bd-11e9-93cf-5517e90a345c.png)

Bing maps ne semble pas utiliser de couleur de bâtiment du tout :
![Capture du 2019-08-08 09-20-08](https://user-images.githubusercontent.com/11553211/62682999-c4030300-b9bd-11e9-87a0-b928e25fce0b.png)

Pareil pour ViaMichelin :
![Capture du 2019-08-08 09-21-09](https://user-images.githubusercontent.com/11553211/62683069-e6951c00-b9bd-11e9-97a0-dd65641acac8.png)

2. Les données me paraissent trop imprécises pour être utiles : quand on désigne un bâtiment comme "rouge" dans les données, en réalité, il est couleur brique, rouge carmin, rouille. Bref, la représentation cartographique ne me parait **pas apporter une information utile**, au contraire, j'ai l'impression que ça pollue **la lisibilité**.

Dans les arguments positifs, il me semble donc qu'il ne reste plus que "le rendu entraîne la création de données" qui ne me parait pas suffisant dans ce cas précis.

En l'état des choses je suis donc favorable à retirer la coloration des bâtiments.

**Comment by frodrigo** [comment]
* En renseignant les matériaux que les couleurs le résultat est mieux
* Ça a était fait surtout pour de la scène 3D

En vue du dessus ça projette la couleur de la façade sur le toit. Il n'y a pas de bonne façon de faire pour colorier le toit avec Mapbox GL.

**Comment by francois2metz** [comment]
J'aimerai tester ce rendu un moment avant de trancher.
