### ISSUE TITLE
Rendu des voies privées

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#13]
Les [_highway=service_ avec _access=private_](https://overpass-turbo.eu/s/Lhq) me paraissent apparaître trop proéminentes sur la carte, réduisant la visibilité générale.

Exemple :
![Capture du 2019-08-02 09-44-58](https://user-images.githubusercontent.com/11553211/62353256-86f4c780-b50a-11e9-8163-aa9157ec2e73.png)

Le problème est que l'on ne peut pas vraiment différencier les petites voies d'accès, comme on voit sur l'exemple ci-dessus, des voies qui desservent de plus grosses résidences, comme ici :
![Capture du 2019-08-02 09-53-05](https://user-images.githubusercontent.com/11553211/62353632-5a8d7b00-b50b-11e9-91a0-d9486ec9e6d4.png)
Or il me semble que l'on ne veut pas changer la visibilité de ces dernières.

3 solutions pour ces petites voies :
1. On ne change rien
2. On réduit la visibilité de ces éléments : largeur du trait et/ou couleur mais aussi les faire disparaître à des niveaux de zoom faibles
3. On utilise un tag spécifique à ces voies d'accès pour personnaliser leur affichage, _[service=driveway](https://wiki.openstreetmap.org/wiki/FR%3ATag%3Aservice%3Ddriveway)_ me paraît tout indiqué pour ça.
Cela pourrait les différencier des _service=parking_aisle_ (même si certaines sont encore indiqués comme étant des parking_aisle [comme sur cet exemple](https://www.openstreetmap.org/way/703016283))

La dernière option me paraît la bonne ... banco ?

PS : Bon point à ne pas changer : les voies passant sous un bâtiment sont bien rendues en pointillés :
![Capture du 2019-08-02 09-45-46](https://user-images.githubusercontent.com/11553211/62353288-9d028800-b50a-11e9-810f-4153896f7279.png)

**Comment by francois2metz** [comment]
Ah ouais c'est mieux le driveway. Je ne sais pas si le rendu sera correct, mais au moins les données seront bonnes.

**Comment by overflorian** [comment]
Je viens de préciser les données sur toute la commune.
@francois2metz tu veux te lancer sur un rendu spécial service=driveway tel que décrit plus haut ?

**Comment by francois2metz** [comment]
Voila le rendu proposé:

![Screenshot_2019-08-03 OSM Bright - TileServer GL](https://user-images.githubusercontent.com/86659/62412209-6f4b3b00-b5ff-11e9-8564-53418ea656a1.png)

**Comment by overflorian** [comment]
Ca déchire. Et si on les faisait disparaître en zoom 15 et plus petit ? A ce niveau là, on est déjà loiiiiin
![Capture du 2019-08-06 11-29-31](https://user-images.githubusercontent.com/11553211/62528664-7fe8f480-b83d-11e9-8faf-0a1e4a1cf4b1.png)

**Comment by francois2metz** [comment]
Un peu compliqué. Le plus haut niveau de zoom généré est le 14 et c'est le niveau de zoom minimum affiché sur osmontrouge en raison de la bbox.

**Comment by francois2metz** [comment]
En travaillant sur un projet secret, je me suis rendu compte qu'on pouvait spécifier le niveau de zoom minimum sur un layer. J'ai caché les les voies de services au dessous de 16.

**Comment by overflorian** [comment]
J'adooore les projets secrets ! Merci batman, ça rend super bien. Notre carte commence à déchirer le farfadet sévère.

**Comment by overflorian** [comment]
J'en ai fait un peu de pub https://twitter.com/osmontrouge/status/1159367928489357312
