### ISSUE TITLE
Fermer des issues

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#15]
Je trouve que le gestionnaire de ce repo se repose trop sur ses lauriers. S'il passait plus de temps à traiter les issues qu'à designer des [icônes toutes pourries](https://github.com/osmontrouge/osmontrouge/issues/14), peut-être que ce projet avancerait plus !! 🤔🤔🤔🤔

Quid de [cette issue](https://github.com/osmontrouge/osmontrouge/issues/14) que j'ai soumise il y a 13 minutes ???? Merci monsieur Langereau.
🤔🤔🤔🤔😡🤬😠💣💥💀

**Comment by francois2metz** [comment]
voila

**Comment by overflorian** [comment]
You got me.
