### ISSUE TITLE
Afficher les bâtiments remarquable

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#18]
J'ai terminé de mapper les bâtiments officiellement reconnus comme remarquables cf. https://wiki.openstreetmap.org/wiki/Montrouge#B.C3.A2timents_remarquables

Est-ce qu'un filtre les affichant serait une bonne idée ? J'hésite car peut-être que l'on préfère afficher les bâtiments "qui valent le détour" et que nous sélectionnons de manière plus subjective ?
Certains des bâtiments inscrits au registre ne sont pas beaux. Ils ont un intérêt patrimonial mais pas touristique.

**Comment by francois2metz** [comment]
Je vais les rajouter pour voir. Je ferme car déjà dans #3
