### ISSUE TITLE
Créer une page /réutilisations

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#24]
Et si on créait une page listant les réutilisations ?
Voici le wording et les illustrations que je propose :

OpenStreetMap est un projet collaboratif. Ses données sont utilisées par de nombreux acteurs. À Montrouge en particulier, à chaque fois que nous réalisons une mise à jour, les acteurs suivants les utilisent :

### Vélib'
![63158496-a8c97080-c019-11e9-8fac-6555223b9e4d](https://user-images.githubusercontent.com/11553211/66125380-13913400-e5e7-11e9-9823-dd94447d2452.jpg)
Les bornes de Vélib' affichent un plan de quartier utilisant les donnés d'OpenStreetMap

### Cityscoot
![61780748-596d9700-ae03-11e9-8e22-3e89358a9642](https://user-images.githubusercontent.com/11553211/66125393-1c820580-e5e7-11e9-9b82-add0fad38292.jpg)
L'appli mobile Cityscoot affiche tous les trottoirs de la ville grâce aux données OpenStreetMap

### Vallée Sud
![IMG_20191003_140937](https://user-images.githubusercontent.com/11553211/66125699-fdd03e80-e5e7-11e9-8c5f-97682d20fcce.jpg)
[Le site Internet de l'intercommunalité](http://www.valleesud.fr) dont Montrouge fait partie utilise OpenStreetMap pour une plus grande précision.

### RATP
![62951261-ef388880-bde9-11e9-9ee0-ffd4a29fa15e](https://user-images.githubusercontent.com/11553211/66125398-2146b980-e5e7-11e9-821d-deed72a52bb1.jpg)
Les bornes interactives dans le métro affichent un plan d’Île-de-France grâce aux données OpenStreetMap

### Île-de-France Mobilités
![61780870-a05b8c80-ae03-11e9-921c-7d06fdefde83](https://user-images.githubusercontent.com/11553211/66125415-286dc780-e5e7-11e9-9005-d1ca4a271d7c.jpg)
Les applis Via Navigo et Geovelo utilisent les données d'OpenStreetMap pour faire des calculs d'itinéraire adaptés aux vélos

De nombreuses autres applications sont basées sur OpenStreetMap, dont par exemple Maps.me ou OsmAnd.
Parmi les autres ré-utilisateurs on trouve la gendarmerie Nationale, la SNCF, data.gouv.fr...

**Comment by francois2metz** [comment]
C'est en ligne ! https://osmontrouge.fr/reuses

**Comment by overflorian** [comment]
trop bien ! je découvre ça à l'instant, merci
