### ISSUE TITLE
Mapillary améliorations

### ISSUE THREAD

**Issue by Phyks** [osmontrouge/osmontrouge#27]
- [ ] Sur mon téléphone (Firefox à jour), l'image Mapillary ne s'affiche pas sur https://osmontrouge.fr/mapillary=@48.815003,2.314875,15.00/360/j4OMwuTjjYBZ7EelVvaR8g

- [x] il serait pratique d'avoir l'angle sur la photo dans l'URL pour partager facilement la vue courante.

**Comment by francois2metz** [comment]
J'ai rajouté l'angle dans l'url. Pas moyen de faire mieux avec l'orientation verticale.

**Comment by francois2metz** [comment]
J'ai testé chez moi, j'ai pu charger l'image en question. Tu peux réessayer ?

**Comment by Phyks** [comment]
En effet, ça fonctionne !
