### ISSUE TITLE
Brancher mapillary (seulement sur nos images)

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/osmontrouge#5]
- [x] voir la couverture
- [x] clic sur une trace pour afficher le viewer
- [x] esc pour fermer le viewer
- [x] une meilleure icône
- [x] un meilleur effet sélectionné
- [x] quelques informations sur le fonctionnement
- [x] filtrer les images dans le viewer

**Comment by francois2metz** [comment]
J'ai branché une première version fonctionnelle de mapillary. On peut visualiser les endroits disponible et cliquer pour faire apparaitre le viewer.
La liste des utilisateurs autorisé est en dur ici: https://github.com/osmontrouge/osmontrouge/blob/2cd63f642cdc92eeb6e08077f05fa9906442fc94/index.js#L37-L41

![mapillary](https://user-images.githubusercontent.com/86659/55932889-ba45da80-5c2b-11e9-90eb-c09c474d4090.gif)

**Comment by overflorian** [comment]
Super bien intégré ! Merci. Je trouve que cette fonctionnalité est néanmoins un peu trop planquée derrière cette petite icône presque invisible.
Proposition : Rajouter (sans enlever l'icône existante) un bouton dans le menu de gauche.

**Comment by francois2metz** [comment]
A la base je ne suis pas chaud, mais pourquoi pas.

T'aurais une idée du type de bouton ?
