### ISSUE TITLE
Implémenter un rendu indoor + multi-niveaux

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/osmontrouge#7]
ça serait top d'avoir un openlevelup (en plus beau !) sur notre site pour rendre correctement le marché de Montrouge.
A terme l'idée est de le faire fonctionner avec des lieux qui sont certes hors du territoire communal mais importants tout de même :
-le centre commercial de la vache noire
-le centre commercial

Ouch ça pique niveau technique, je sais :P

**Comment by francois2metz** [comment]
Tu me casse la surprise sur laquelle j'étais en train de travailler ! (Pas de code encore)

**Comment by overflorian** [comment]
T'es pas sérieux ?? Trop cool. Promis ça sortira pas d'internet ^^

**Comment by overflorian** [comment]
hey, tu as pu avancer là-dessus ?

**Comment by francois2metz** [comment]
J'ai un rendu en v0 pour l'ile de france disponible sur https://osm-indoor.2metz.fr

Quelques exemples:
- Marché montrouge: https://osm-indoor.2metz.fr/#19.58/48.8160189/2.3205882
- Montparnasse: https://osm-indoor.2metz.fr/#18.19/48.840838/2.320343
- Gare de l'est: https://osm-indoor.2metz.fr/#18.19/48.876869/2.359795

Il y a des milliards de trucs a gérer encore.

**Comment by overflorian** [comment]
ça déchire totalement ! TU déchires totalement
